network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s8:
      dhcp4: true
      gateway4: 192.168.1.150
      nameservers:
        addresses:
          - 192.168.1.150
#         - 10.140.52.20
